### PR TITLE
fix: Paste into find-input

### LINKED ISSUE #572: Pasting a string in sidebar search field when not pinned is impossible
[Affected versions]:
- Nightly 51.0a1
- Tab Center v1.24.0

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Tab Center add-on version (v1.24.0) was installed on a new clean profile.
- Tab center Sidebar is kept unpinned.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites.
2. Copy a string from anywhere.
3. Hover the Sidebar and right click in the search field.
4. Choose to paste the copied string.

[Expected result]:
- Copied string is correctly pasted in the search box and the filtering is performed.

[Actual result]:
- Copied string is not pasted in the search box.

[Notes]:
- This issue is not reproducible when Sidebar is pinned so I assume it should work also when not pinned.
- Added a screen recording with the issue http://goo.gl/a59Gu5 .

### PR DESCRIPTION
**Pull request by ericawright**
r: @bwinton 

Add timeout to mouseleave `exit` event to fix #572 in an alternate way. 
Also lets user correct position if they overshoot.

fixes: #572 (again).

### CODE REVIEW

File: verticaltabs.js [hunk 1]
```diff
@@ -455,20 +455,18 @@ VerticalTabs.prototype = {
     });
 
     leftbox.contextMenuOpen = false;
-    leftbox.searchMenuClosed = false;
+    // leftbox.searchMenuClosed = false;
```
Comment (bwinton) [inline verticaltabs.js]: We can just remove this code, instead of commenting it out…  😉
