### PR TITLE
Fix: "Close Other Tabs" confirmation dialog

### LINKED ISSUE #937: [Reverse Tab Order] "Close Other Tabs" confirmation dialog incorrectly counts the pinned tabs
[Affected versions]:
- Firefox 51.0.1 and above
- Tab Center 1.29.0 (built on 2/17/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Tab Center add-on is installed on a new clean profile.
- Reverse tabs order option is checked from "about:addons" page for Tab Center extension.
- Have at least 4 tabs opened and 2 pinned tabs.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Right click an unpinned tab.
3. Click the "Close Other Tabs" option from the context menu.
4. Observe the "Confirm close" dialog.

[Expected result]:
- The confirmation message contains the number of tabs minus the pinned ones.

[Actual result]:
- Pinned tabs are also counted in the confirmation message.

[Notes]:
- Only the unpinned tabs are closed if you confirm the dialog.
- Here is a screen recording of the issue: 
close other tabs incorrectly counts the pinned tabs

### PR DESCRIPTION
**Pull request by ericawright**
r=@bwinton

- make numPinnedTabs a method on TC, 
- override `warnAboutClosingTabs` to…check properly for numpinnedtabs

Fixes #937.

Note: I'm sad that we can't use the binding to overrride tabbrowser - our verticalTabs.js file is getting out of control

### CODE REVIEW

File: verticaltabs.js [hunk 1]
```diff
@@ -290,13 +347,7 @@ VerticalTabs.prototype = {
...
     let oldAddTab = window.gBrowser.addTab;
     window.gBrowser.addTab = function (...args) {
-      let numPinned = 0 ;
-      for (let i = 0; i < this.tabs.length; i++) {
-        if (!this.tabs[i].pinned) {
-          continue;
-        }
-        numPinned += 1;
-      }
+      let numPinned = window.numPinnedtabs();
```
Comment (arai-a) [inline verticaltabs.js]: should be `window.VerticalTabs.numPinnedtabs()`

Comment (arai-a) [inline verticaltabs.js]: fixed in #942

Comment (ericawright) [inline verticaltabs.js]: yes it should be, thank you
