### PR TITLE
fix: Run the initialization code for _all_ the new windows.

### LINKED ISSUE #529: TabCenter should be marked as multiprocess compatible
Currently TabCenter isn't marked as multiprocess compatible. Although it seems to work, there may still be some incompatibilities that are masked by Firefox's shims.

The shims may also lead to performance issues, although I doubt TabCenter would really be hitting those that hard: https://developer.mozilla.org/Add-ons/SDK/Guides/Multiprocess_Firefox_and_the_SDK#Testing_with_shims_enabled

Setting the flag for TabCenter should be as simple as adding the following to `package.json`:

```
"permissions": {
  "multiprocess": true
}
```

Obviously, it should be tested to make sure it does work.

### PR DESCRIPTION
**Pull request by bwinton**
Bail on updating stuff if we don't have a linkedBrowser yet.
Don't add two VerticalTabs instances to a window.
Watch for the `domwindowopened` event to catch all opening windows.
Mark the add-on as multiprocess-compatible.

Reviewer: @ericawright
Fixes #529.

### CODE REVIEW

File: verticaltabs.js [hunk 1]
```diff
@@ -250,6 +253,31 @@ VerticalTabs.prototype = {
...
+      // Make the popup's starting margin negative so that the leading edge
+      // of the popup aligns with the window border.
+      let elementRect = aElement.getBoundingClientRect();
+      if (popupDirection === 'rtl') {
+        let offset = elementRect.right - rect.right;
+        autocomplete.style.marginRight = offset + 'px';
+      } else {
+        let offset = rect.left - elementRect.left;
+        if (mainWindow.getAttribute('tabspinned') !== 'true') {
+          // #main-window[inFullscreen][inDOMFullscreen]
```
Comment (ericawright) [inline verticaltabs.js]: remove?

**Comment by Popog** [comment]
What's the need for `domwindowopened`? What does it catch that `browserWindows.on('open')` doesn't?

**Comment by bwinton** [comment]
`jpm run` then open http://unicode.org/cldr/utility/list-unicodeset.jsp and click on one of the links at the top (like “confusables”)…  I don't know _why_ it doesn't catch that window, but it doesn't.  (And yeah, we could fix that in the addon-sdk, but I want this to work on Release. 😉)
